### ISSUE TITLE
An internal error occurred during: "Scan output folders marked as not derived.".

### ISSUE THREAD

**Issue by ahoehma** [bjmi/jdt.extensions#2]
java.lang.NullPointerException
    at derivedresources.preferences.Preference.getPreferenceStore(Preference.java:35)
    at derivedresources.preferences.Preference$1.getValue(Preference.java:49)
    at derivedresources.preferences.Preference$1.getValue(Preference.java:1)
    at derivedresources.folder.MarkDerivedJob.runInWorkspace(MarkDerivedJob.java:119)
    at org.eclipse.core.internal.resources.InternalWorkspaceJob.run(InternalWorkspaceJob.java:39)
    at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)

**Comment by ahoehma** [comment]
Björn, this error comes from my "dropin"-based installation. Maybe this plugin version is toooo old? :D

**Comment by bjmi** [comment]
Current version of derived resources plugin is 1.4.5 and available via update site. Please try updating first.

**Comment by bjmi** [comment]
Due to missing feedback issue will be closed. Please reopen if required.
